-- 22-01-2018
ALTER TABLE `business_configs` ENGINE = INNODB ROW_FORMAT = COMPACT;
ALTER TABLE `categories` ENGINE = INNODB ROW_FORMAT = COMPACT;
ALTER TABLE `customers` ENGINE = INNODB ROW_FORMAT = COMPACT;
ALTER TABLE `products` ENGINE = INNODB ROW_FORMAT = COMPACT;
ALTER TABLE `sales` ENGINE = INNODB ROW_FORMAT = COMPACT;
ALTER TABLE `sale_amounts` ENGINE = INNODB ROW_FORMAT = COMPACT;
ALTER TABLE `sale_details` ENGINE = INNODB ROW_FORMAT = COMPACT;
ALTER TABLE `sale_sessions` ENGINE = INNODB ROW_FORMAT = COMPACT;
ALTER TABLE `voucher_configs` ENGINE = INNODB ROW_FORMAT = COMPACT;
-- DONE